bert_gen:
  config_path: config.json
  device: cuda
  num_processes: 2
  use_multi_device: false
dataset_path: Data\keqing
mirror: ''
openi_token: ''
preprocess_text:
  clean: true
  cleaned_path: filelists/cleaned.list
  config_path: config.json
  max_val_total: 8
  train_path: filelists/train.list
  transcription_path: filelists/short_character_anno.list
  val_path: filelists/val.list
  val_per_spk: 5
resample:
  in_dir: raw
  out_dir: raw
  sampling_rate: 44100
server:
  device: cuda
  models:
  - config: ./Data/keqing/config.json
    device: cuda
    language: ZH
    model: ./Data/keqing/models/G_0.pth
    speakers:
    - length_scale: 1
      noise_scale: 0.6
      noise_scale_w: 0.8
      sdp_ratio: 0.2
      speaker: "\u79D1\u6BD4"
    - length_scale: 0.5
      noise_scale: 0.7
      noise_scale_w: 0.8
      sdp_ratio: 0.3
      speaker: "\u4E94\u6761\u609F"
    - length_scale: 1.2
      noise_scale: 0.6
      noise_scale_w: 0.8
      sdp_ratio: 0.2
      speaker: "\u5B89\u500D\u664B\u4E09"
  - config: ./Data/keqing/config.json
    device: cuda
    language: JP
    model: ./Data/keqing/models/G_0.pth
    speakers: []
  port: 7860
train_ms:
  base:
    model_image: "Bert-VITS2中日英底模-fix"
    repo_id: Stardust_minus/Bert-VITS2
    use_base_model: false
  config_path: config.json
  env:
    MASTER_ADDR: localhost
    MASTER_PORT: 10086
    RANK: 0
    THE_ENV_VAR_YOU_NEED_TO_USE: '1234567'
    WORLD_SIZE: 1
  model: models
translate:
  app_key: ''
  secret_key: ''
webui:
  config_path: Data/keqing/config.json
  debug: false
  device: cuda
  language_identification_library: langid
  model: models/G_0.pth
  port: 7860
  share: false
